### ISSUE TITLE
Support class option hash for eruby

### ISSUE THREAD

**Issue by jdsutherland** [AndrewRadev/sideways.vim#52] opened 2021-07-04 19:43 UTC
It'd be nice if https://github.com/AndrewRadev/sideways.vim/pull/41 worked for option hashes in eruby:

```erb
<li><%= link_to 'Home', '#', class: 'one two three' %></li>
```

I tried implementing this myself:
```viml
let b:sideways_definitions = [
      \   {
      \     'start':     '<%=\=\s*\%(\k\|\.\|::\)*\k\{1,} ',
      \     'end':       '\s*%>',
      \     'delimiter': ',\s*',
      \     'brackets':  ['([''"', ')]''"'],
      \   },
      \   {
        \     'skip_syntax':             [],
        \     'start':                   "\v<class:\s?'",
        \     'end':                     "'",
        \     'delimited_by_whitespace': 1,
        \     'brackets':                ['', ''],
        \   },
      \   sideways#html#Definition('tag_attributes',      { 'brackets': ['"''<', '"''>'] }),
      \   sideways#html#Definition('double_quoted_class', { 'brackets': ['<', '>'] }),
      \   sideways#html#Definition('single_quoted_class', { 'brackets': ['<', '>'] }),
      \   sideways#html#Definition('double_quoted_style', { 'brackets': ['<', '>'] }),
      \   sideways#html#Definition('single_quoted_style', { 'brackets': ['<', '>'] }),
      \ ]
```
but the existing seemed to take precedence. I'm guessing the regex:
```
'start': '<%=\=\s*\%(\k\|\.\|::\)*\k\{1,}`
```

would have to negative lookahead for `class:`?

**Comment by AndrewRadev** [comment] 2021-07-05 08:43
No, that's fine -- the definitions are all attempted, and the "smallest" match wins. The problem is that the pattern is surrounded by double-quotes, and those evaluate backslashes. If you `echo b:sideways_definitions[1]`, you'll get:

```
{'skip_syntax': [], 'end': '''', 'brackets': ['', ''], 'start': 'v<class:s?''', 'delimited_by_whitespace': 1}
```

And you can see the start pattern starts with `v` instead of `\v`. One option would be to use `\\` in the double-quotes, another is to use single quotes and escape apostrophes by doubling them: `'\v<class:\s?'''`. This is, admittedly, a bit obscure :). You could learn more details from `:help string` and `:help literal-string`.

I'm not sure if I it makes sense to keep this in the default definitions, since it's specific to the rails helper, and not a feature of ERB itself. Still, I guess it wouldn't be a practical problem, and it's true that most ERB is rails... Would you like to see this in the defaults, or are you happy to use this in your own override? If you'd like, you could create a PR with the change, and I can probably be persuaded to merge it.

**Comment by jdsutherland** [comment] 2021-07-05 19:19
I'm fine with having this be an override. I can imagine encountering a gem that use some variation of the name `class` that I'd want to add in.

**Comment by AndrewRadev** [comment] 2023-06-04 09:18
@pooriar I've added support to the repo in the [eruby-classes](https://github.com/AndrewRadev/sideways.vim/tree/eruby-classes) branch. Could you try it out and see if the patterns in that form work?

**Comment by pooriajr** [comment] 2024-11-15 18:37
@AndrewRadev Somehow I missed your response completely, and then wound up on this issue and - to my surprise - saw my own comment and your response. Just updated to the `eruby-classes` branch and it's working splendidly, thank you so much for making one of my favorite plugins even better!

**Comment by AndrewRadev** [comment] 2024-11-15 22:12
@pooriajr I've missed github notifications myself over the last few years, I think it's just a normal result of Microsoft letting github fall apart :).

In any case, I've merged to the main branch, so feel free to switch to it. I'll go ahead and close this issue, but feel free to reopen if you run into problems.

**Closed by AndrewRadev** 2024-11-15 22:12 UTC
